BOARD_TAG = mega2560A
MONITOR_PORT = /dev/serial0
ARDUINO_LIBS = Adafruit_GPS_hw ADXL362 Time SPI
USER_LIB_PATH = /home/pi/sketchbook/libraries
ISP_PROG = usbtiny
CXXFLAGS_STD = -Wno-write-strings -Wno-unused-variable -Wno-sign-compare
include /usr/share/arduino/Arduino.mk
